/*
 * @Author: Elk
 * @Date: 2023-04-27 19:47:58
 * @FilePath: /yaame-h5/src/pages/user_agreement/locale/en-US.js
 * @Description: 
 */
export default {
    't1': '1. Introduction',
    'c1': 'Welcome to the "Yaame" software and related services!',

    't1-1': '1.1 The content, services, ownership, and operation of the "Yaame" software (hereinafter referred to as "the Software") are owned by XAM PTE LTD. ("Yaame" or the "Company"). In order to better serve you, please read and fully understand the terms and conditions of this Agreement, especially the exclusion or limitation of liability, the application of law and the dispute resolution clause (marked in bold), before you start using the Software and related services. You shall ensure that you are a natural person who is at least 18 years of age. If you are under 18 years of age, you shall not register, log in to the Software or use the Services. If you are 18 years of age or older but otherwise do not have the civil capacity appropriate to your conduct, please read this Agreement with a guardian. Please ensure that your guardian agrees to all of your actions, in which case you and your guardian shall be liable for all consequences resulting therefrom in accordance with the law.',

    't1-2': '1.2 If you voluntarily choose to agree to or use the Software and related services, you are deemed to have fully understood this Agreement and agree to be bound by this Agreement and other agreements and rules related to the Software and related services (including but not limited to the Personal Information Protection Policy) as a party to this Agreement. If you do not agree to this Agreement or any of its terms and conditions, you should immediately stop accessing the Software and stop using the related services provided by "Yaame".',

    't1-3': '1.3 If you have any questions, comments or suggestions regarding the content of this Agreement, you may contact the Company through the contact information set forth in Section 12.9 of this Agreement.',

    't2': '2. Application',

    't2-1': '2.1 "User" means the user who directly or indirectly acquires and uses the Software and related services, referred to in this Agreement as "User" or "You". The Software refers to the client application labeled "Yaame" that is legally owned and operated by the Company. The Company reserves the right to unilaterally change the name of the application and website (including but not limited to name change, addition, etc.).',

    't2-2': '2.2 This Agreement is an agreement between you and the Company regarding your registration, login, use of the Software, and access to the relevant services provided by the Software. The Company has the right to unilaterally decide, arrange or designate its affiliates, controlled companies, successor companies or third party companies approved by the Company to continue to operate the Software and to provide some/all of the Services to you in accordance with the needs of the Software and related services or operations. You understand and agree that by accepting the content of the relevant services, you are deemed to accept that the relevant rights and obligations are also governed by this Agreement.',

    't2-3': '2.3 Considering the continuous high speed development and evolution of the Internet service, this Agreement and related service agreements, rules, etc. may be updated by the Company, and after the update, the Company will announce the updated content on the relevant page in advance, and you agree to undertake the obligation to read, comment and confirm the updated content in a timely manner. If you do not agree with the updated content, please immediately stop accessing and using the Software and cancel the acquired services; if you choose to continue using the Software after the update, you will be deemed to have accepted the updated content.',

    't3': '3. About the account',

    't3-1': '3.1 Account registration and login',

    't3-1-1': '3.1.1 You understand and agree that in order to fully use the Software and related services, if you are an adult over 18 years of age, you may register for an account on your own. This account is your credentials to use the Software and related services as a registered user. If you are a minor under the age of 18, please stop registering or using the Services under the Software immediately. We do not recommend or support the use of the Software and related services by minors in any way, and the Software will rely on the personal information provided by the user to determine whether the user is a minor. If you are under 18 years of age to register the Software and use the relevant services with false identity information, or use the Software and related services using adult accounts, you should understand that violation of laws and regulations, the content of this Agreement, Yaame has the right to make corresponding penalties, you and your guardian shall bear all the consequences caused by the provisions of the law.',

    't3-1-2': "3.1.2 You need to register an account before using the services related to this Agreement, the account should be registered using a real and valid cell phone number, please use the cell phone number that is not bound to the Software account and has not been blocked by the Company under this Agreement to register. The Company may change the way of account registration and binding without prior notice to you and according to the needs of the product. In order to complete the aforementioned cell phone number binding registration method, you agree that the Software will use the cell phone number you provide when you register your account or automatically extract your cell phone number information for registration. You agree to authorize the operator to automatically extract your cell phone number for authentication and use it for account registration, and you agree to abide by the operator's relevant terms of service, and your account registration will be completed if the operator's authentication of your cell phone number is successful. If you do not agree to give authorization to the operator, or do not agree to the operator's relevant terms of service, or if your cell phone number authentication fails, you can manually modify the cell phone number extracted by the operator and take the verification code to register.",

    't3-2': '3.2 Account Content',

    't3-2-1': '3.2.1 You understand and promise that the content of the account set by you (including but not limited to account name, avatar, etc.) meets the following requirements:',

    't3-2-1-1': '(1) shall not violate national laws and regulations or be harmful to social morals and ethics;',
    't3-2-1-2': '(2) shall not violate the relevant rules of the company;',
    't3-2-1-3': '(3) shall not damage the legitimate rights and interests of others, including but not limited to using the name of others to register accounts, accounts containing content that violates the legitimate rights and interests of others (including but not limited to reputation, portrait rights, privacy rights, intellectual property rights), etc;',
    't3-2-1-4': '(4) shall not contain content of an advertising or promotional nature in the account name or avatar, etc;',
    't3-2-1-5': '(5) shall not contain other content that may affect the normal operation of the Software and related services. The Company has the right to review the content of your account, make unilateral judgment, and has the right to take measures such as deleting prohibited content, banning, blocking accounts, and canceling accounts according to the severity of the circumstances, and such review does not exempt you from the relevant legal responsibilities.',

    't3-2-2': '3.2.2 When you register, use and manage your account, you guarantee the authenticity, legality and validity of the information you fill in and use when registering your account, including but not limited to your name, contact number, address, etc. In accordance with national laws and regulations, in order to use the Software and related services, you need to fill in real identity information and/or complete real name authentication, and pay attention to update the above-mentioned information in a timely manner. Otherwise, the Company has the right to refuse to provide you with relevant services, or you may not be able to use the Software and related services, or some functions may be restricted in the process of use.',

    't3-3': '3.3 Account Ownership and Use',

    't3-3-1': '3.3.1 The ownership of your account registered with the Software belongs to the Company. After you complete the application registration procedures, you obtain the right to use the account, which belongs to you (the initial applicant for registration) only, and it is prohibited to give, borrow, rent, transfer, sell or otherwise license the account to others in any form. If the Company discovers or has reasonable grounds to believe that the user is not you (the initial applicant), or if the Company has operational needs, the Company has the right to immediately suspend or terminate the provision of the Services to you or cancel your account.',

    't3-3-2': '3.3.2 You are responsible for keeping your registered account information and account password in a safe place, and if your misuse of them results in theft of your account number or password, you will be responsible for any losses or liabilities associated with such theft. You are legally responsible for all activities you engage in using your registered account, including but not limited to any data modification, speech publication, payment and other operational acts you perform on the Software.',

    't3-3-3': '3.3.3 You shall comply with the terms of this Agreement, the correct and appropriate use of the services related to this Agreement, if you violate any of the terms of this Agreement and other rules of the platform, Yaame will notify you in accordance with laws and regulations and the provisions of this Agreement to interrupt or terminate the service to you.',
    
    't3-4': '3.4 Account Banning and Recovery',

    't3-4-1': '3.4.1 If your account has the following circumstances, the company has the right to unilaterally initialize, ban or simply cancel or recall your account without legal liability to you. Your account will no longer be able to log in, and the corresponding services will be terminated at the same time:',

    't3-4-1-1': '(1) The law has clear provisions Yaame to further check and verify your information, the company can not get in touch with you, or the information you provide is not true;',
    't3-4-1-2': '(2) You violate the relevant provisions of clauses 5.2, 6.2 and 6.3 of this Agreement',
    't3-4-1-3': '(3) You violate one or several other provisions of this Agreement and the Company unilaterally bans or recalls your account.',

    't3-5': '3.5 Account Modification and Cancellation',

    't3-5-1': '3.5.1 You can modify your personal information (avatar, nickname, birthday, dating voice) by clicking "Edit Profile" on the "My" page.',
    't3-5-2': "3.5.2 You can apply for account cancellation in App-My-Settings-Registration. In order to ensure the safety of the user's account, the customer service staff has the right to verify the identity of the user to ensure that the account to be cancelled is truly owned by the user. The company will assist you to cancel your account after completing reasonable and necessary verification of your personal identity, security status, device information, etc. Unless otherwise provided by laws and regulations, the company will delete all information about your account at your request, but please note that once the account is cancelled, it cannot be restored, and the rights, levels, and relationship chains corresponding to the account will be permanently erased, and it is impossible to retrieve any information or content in the account, and any inconvenience or consequence caused by this will be at your own risk. If the account has illegal or illegal behavior before cancellation, the related behavior or responsibility will not be exempted or mitigated by account cancellation.",

    't3-6': '3.6 Handling of gold coins',
    't3-6-1': '3.6.1 If your registered account has not been logged in or used for more than 180 days, the platform has the right to recycle the gold rewards in your account, i.e. all gold rewards and other products generated and obtained in your account will be zeroed out.',

    't4': "4. Protection of Users' Personal Information",

    't4-1': '4.1 Personal information protection policy',

    't4-1-1': '4.1.1 The company attaches great importance to the protection of your personal information and has formulated the "Personal Information Protection Policy", which you can also check through "My" - "Settings" - "Personal Information Protection Policy You can also check it through "My" - "Settings" - "Personal Information Protection Policy" page, and you will be deemed to have accepted the Personal Information Protection Policy if you confirm and agree to use the services provided by the Software.',

    't4-2': '4.2 Provision and Handling of User Personal Information',

    't4-2-1': '4.2.1 You may need to fill in or submit some necessary personal information (including but not limited to your name, telephone number, geographic location information, equipment information, etc.) in the process of registering an account or using the Service so that the Company can provide you with better services and technical support. You understand and agree that the Company has the right to collect, use (including commercial cooperation use), store and share your personal information in compliance with the laws and regulations, this Agreement and the Personal Information Protection Policy, and that the Company will protect your right to view, modify and delete the relevant personal information in accordance with the law.',

    't4-2-2': '4.2.2 You may inquire, access, modify and delete your submitted personal information at any time, and you understand and agree that for security and identification (such as account or password retrieval appeal services, etc.) reasons, you may not be able to modify the initial registration information and other verification information provided during registration.',

    't4-3': '4.3 Disclosure and Use of User Personal Information',

    't4-3-1': '4.3.1 The Company will not disclose your personal information to any company, organization, etc. outside the Company without your consent, except in the following specific circumstances:',

    't4-3-1-a': 'a) Where your prior express authorized consent is obtained;',
    't4-3-1-b': 'b)Where you share, transfer or disclose it to other companies, organizations and individuals on your own;',
    't4-3-1-c': 'c)if it is related to national security, national defense security, public safety, public health, or significant public interest',
    't4-3-1-d': 'd) disclosed or provided as required by applicable laws and regulations, mandatory administrative and judicial requirements, or in connection with crime investigation, prosecution, trial and sentence enforcement, etc. Subject to laws and regulations, when the Company receives a request for disclosure of the aforementioned information, the Company will request the other party to produce legal documents corresponding to it, such as a subpoena or letter of inquiry. The company will examine all requests carefully to ensure that they have a legal basis and are limited to data that the administrative and judicial authorities have a legal right to obtain for specific investigative purposes;',
    't4-3-1-e': 'e) To the extent permitted by laws and regulations, as necessary to safeguard the legitimate rights and interests of other users of the Software, the Company and its affiliates and control companies in life and property or to ensure the safe and stable operation of the Software, such as finding, preventing and dealing with fraud and other illegal activities and reducing credit risks (excluding the disclosure or provision of personal information to the public for profit-making purposes in violation of the commitments made in this Agreement);',
    't4-3-1-f': 'f) Where personal information is collected from lawful public disclosures, such as lawful news reports, government information disclosure and other channels;',
    't4-3-1-g': 'g) where your personal information has been specially processed in such a way that a specific individual cannot be identified and cannot be recovered.',

    't4-4': '4.4 Third party provision of user personal information',
    't4-4-1': '4.4.1 Considering that the Software and related services may include or link to information or other services (including websites) provided by third parties. You are aware and understand that third parties operating such services may ask you to provide personal information. In particular, the Company reminds you that you are required to read the user agreements, personal information protection policies and other relevant terms and conditions of such third parties very carefully, to protect your personal information properly, and to provide it to such third parties only when necessary. This Agreement and other agreements and rules relating to the Software and related services (including but not limited to the Personal Information Protection Policy) shall not apply to services provided by any third party, and the Company shall not be liable for any consequences that may arise from the use of personal information provided by you by a third party.',

    't5': '5. Code of Conduct for Users',
    't5-1': '5.1 Independence of user behavior',
    't5-1-1': '5.1.1 Any content you transmit or post in or through the Software does not reflect or represent, and shall not be deemed to reflect or represent, the views, positions or policies of the Company, and the Company shall not be liable for any of them.',
    't5-2': '5.2 Prohibited User Conduct',
    't5-2-1': '5.2.1 You may not use the Software account or the Services to do any of the following:',
    't5-2-1-a': "a) submitting or publishing false information, or stealing another person's avatar or information, impersonating or using another person's name",
    't5-2-1-b': 'b) Containing content of an advertising or promotional nature in the content of the registered account, or publishing the aforementioned content through the account, or forcing or inducing other users to follow, click on linked pages or share information;',
    't5-2-1-c': 'c) falsifying facts or concealing the truth in order to mislead or deceive others',
    't5-2-1-d': 'd) Using technical means to create false accounts in bulk;',
    't5-2-1-e': 'e)Using the Software account or service to engage in any illegal or criminal activities;',
    't5-2-1-f': 'f) producing or publishing methods or tools related to the above acts, or operating or disseminating such methods or tools, whether or not such acts are for commercial purposes',
    't5-2-1-g': 'g) Knowing or should know that the advertising information, links or information is false and still deal with them, threatening the company with compensation or indemnity in various forms;',
    't5-2-1-h': 'h) Other acts that violate the provisions of laws and regulations, violate the legal rights of other users, interfere with the normal operation of the Software and related services, or are not expressly authorized by Company.',

    't5-2-2': '5.2.2 Unless otherwise permitted in writing by the Company, you may not engage in any of the following acts:',
    't5-2-2-a': 'a) Remove information about the copyright on the Software and its copies;',
    't5-2-2-b': 'b) Reverse engineer, reverse assemble, reverse compile, or otherwise attempt to discover the source code of the software;',
    't5-2-2-c': 'c) using, renting, lending, copying, modifying, linking, reproducing, compiling, publishing, publishing, establishing mirror sites, etc. of the content of which the company owns intellectual property rights;',
    't5-2-2-d': 'd) to copy, modify, add, delete, hook up, run or create any derivative works of the software or the data released into the memory of any terminal during the operation of the software, the interaction data between the client and the server during the operation of the software, and the system data necessary for the operation of the software, in the form of, but not limited to, using plug-ins, plug-ins or non-authorized third-party tools/services to access the software and related systems;',
    't5-2-2-e': 'e) adding, deleting, changing the functionality or operating effects of the Software by modifying or falsifying instructions or data in the operation of the Software, or operating or disseminating the Software or methods used for such purposes to the public, whether or not such actions are for commercial purposes;',
    't5-2-2-f': 'f) Login or use the Software and Services through third-party software, plug-ins, plug-ins, or systems not developed or authorized by the Company, or create, distribute, or disseminate third-party software, plug-ins, plug-ins, or systems not developed or authorized by the Company.',
    't5-2-2-g': 'g) domain hijacking, malicious jumping, malicious brush volume, cheating, etc. of the links or promotional contents involved in the Software and Services',
    't5-2-2-h': `h) Unauthorized use of programs or devices (including but not limited to any robots, web spiders, web crawlers, etc.) to monitor, copy, transmit, display, mirror, upload, or download the content of the Software and related services. i) Private use of the Company's products and services including but not limited to "Company", "Yaame", etc, "Yaame" and any other trademarks, service marks, trade names, domain names, website names, or other distinctive brand features (collectively, the "Marks"), display, use, or apply for registration of a trademark for the foregoing Marks, either alone or in any combination, or register a domain name for the Software and related services, register a domain name, or perform any other act that expressly or impliedly gives others the right to display, use, or otherwise deal with such Marks.`,

    't5-2-3': '5.2.3 If you engage in any of the conduct described in 5.2.2, you will be fully responsible for that conduct. The Company reserves the right to take measures including, but not limited to, banning, account freezing, account cancellation, etc., depending on the severity of your prohibited behavior. If you cause damage to the Company, you shall fully compensate for such damage.',

    't5-3': '5.3 Judgment of independence of user behavior',

    't5-3-1': '5.3.1 If the Company has reason to believe that your behavior violates or may violate the provisions of this Agreement, the Company may independently judge and deal with it, and at any time has the right to terminate the provision of services to you without prior notice and pursue related responsibilities in accordance with the law.',

    't6': '6. User Content Specifications',
    't6-1': '6.1 Scope of content:',

    't6-1-1': '6.1.1 The content described in this Article refers to any content created, uploaded, copied, published or disseminated by you in the course of using the Service, including but not limited to account avatar, name, user description and other registration information and authentication information, or text, voice, pictures, videos, graphics and other sent, replied or auto-reply messages and related link pages, and all other content generated by using the account or the Service.',

    't6-2': '6.2 Prohibition on Posting Illegal Content:',

    't6-2-1': '6.2.1 You may not use the Software Account or related services to create, upload, copy, publish, or transmit content that is prohibited by laws, regulations, and policies as follows',

    't6-2-1-a': 'a) that opposes the basic principles established by the Constitution',
    't6-2-1-b': 'b) that endangers national security, leaks state secrets, subverts state power, or undermines national unity',
    't6-2-1-c': 'c) damage to national honor and interests;',
    't6-2-1-d': 'd) incite ethnic hatred, ethnic discrimination, and undermine national unity',
    't6-2-1-e': "e) undermining the state's religious policy, promoting evil cults and feudal superstitions",
    't6-2-1-f': 'f) spreading rumors, disturbing social order and destabilizing society',
    't6-2-1-g': 'g) spreading obscenity, pornography, gambling, violence, murder, terror or abetting crime',
    't6-2-1-h': 'h) insulting or slandering others and infringing on their legitimate rights and interests',
    't6-2-1-i': 'i) does not comply with the bottom line of laws and regulations, the bottom line of the socialist system, the bottom line of national interests, the bottom line of the legitimate rights and interests of citizens, the bottom line of social public order, the bottom line of morality and the bottom line of information authenticity requirements',
    't6-2-1-j': 'j) Information containing other contents prohibited by laws and administrative regulations.',

    't6-3': '6.3 Prohibition of publishing infringing and illegal contents:',
    't6-3-1': '6.3.1 The Company is committed to making the release of information, interactive exchanges, and comments a civilized, rational, friendly, and high-quality exchange of opinions. While promoting the development of the business of publishing information, interactive exchanges and comments, we will continuously strengthen the corresponding information security management capabilities, improve the self-regulation of publishing information, interactive exchanges and comments, effectively fulfill our social responsibilities, comply with national laws and regulations, respect the legitimate rights and interests of citizens and respect social order and morality.',
    't6-3-2': '6.3.2 You shall not use the Software account or the Services to create, upload, copy, publish or disseminate any content that interferes with the normal operation of the Company and infringes the legitimate rights and interests of other users or third parties, including but not limited to',

    't6-3-2-a': 'a) containing any sexual or sexually explicit content;',
    't6-3-2-b': 'b) containing abusive, threatening or intimidating content',
    't6-3-2-c': 'c) containing harassment, advertising, promotion, malicious information, and deceptive information',
    't6-3-2-d': 'd) that involve the privacy, personal information or data of others',
    't6-3-2-e': 'e)infringes on the legal rights of others such as reputation, portrait rights, intellectual property rights, trade secrets, etc;',
    't6-3-2-f': 'f) information containing other content that interferes with the normal operation of the Software or Services and infringes on the legitimate rights and interests of other users or third parties.',

    't6-3-3': '6.3.3 If you post content that violates the foregoing prohibitions, the Company shall have the right to remove such allegedly infringing content upon receipt of notice from the right party or related parties. If the Company, its affiliates, controlled companies and successor companies suffer losses (including but not limited to economic and goodwill losses) as a result of your infringement, you shall also compensate the Company, its affiliates, controlled companies and successor companies in full for all losses suffered.',

    't7': '7. Data Storage',

    't7-1': '7.1 The Company provides information network storage space for the content (including but not limited to text, images, video, audio, music compositions, sounds, lines, dialogues, etc. included in the video and/or audio) that you post and upload through the Software.',

    't7-2': '7.2 The Company is not responsible for the deletion or storage failure of your relevant data in the Service.',
    't7-3': '7.3 The Company may, at its sole discretion, determine the maximum storage period for your data in the Service and allocate maximum storage space for the data on its servers. You may back up the relevant data in the Service by yourself as needed.',
    't7-4': '7.4 If you stop using the Service or the Service is terminated, the Company may permanently delete your data from the server. The Company is not obligated to return any data to you after the Service is discontinued or terminated.',

    't8': '8. Exclusion of Liability',
    't8-1': '8.1 You understand and agree that the Company is only providing a platform for you to share, transmit and access information and that you are responsible for all actions under your registered account, including any content you transmit and any consequences arising therefrom. You shall exercise your own judgment regarding the Company and the content on the Service and bear all risks arising from the use of the content, including risks arising from reliance on the accuracy, completeness or usefulness of the content. The Company cannot and will not be liable for any loss or damage resulting from your conduct. If you discover that anyone is violating this Agreement or using the Service in any other inappropriate manner, please report or complain to the Company immediately, as detailed in clause 12.9 of this Agreement.',
    't8-2': '8.2 You understand and agree that due to business development needs, the Company reserves the right to unilaterally change, suspend, terminate or withdraw all or part of the Service without being responsible or liable to you for any compensation.',
    't8-3': '8.3 You understand and agree that in the course of using the Service there exists information from any other person, including misleading, deceptive, threatening, defamatory, offensive or illegal information, or anonymous or impersonal information that violates the rights of others, and the conduct accompanying such information, you are required to use your own independent judgment to determine the truthfulness and accuracy of the foregoing information, and to independently bear the possible adverse The Company shall not be liable for any losses incurred by you or third parties as a result.',
    't8-4': '8.4 You understand and agree that the Company may need to overhaul or maintain the Software or related equipment on a regular or irregular basis, and that the Company shall not be liable for any interruption of the Services for a reasonable period of time due to such circumstances.',

    't8-5': '8.5 You understand and agree that the Company shall not be liable for any defects in the quality of the following products or services provided to you by the Company and any losses arising therefrom:',
    't8-5-a': 'a) Services provided to you by the Company free of charge;',
    't8-5-b': 'b) any products or services that the Company gives to you.',

    't8-6': "8.6 In no event shall Company be liable to you or a third party for any use of the Service in any way, or for any loss or damage, pecuniary or otherwise, that may result from the inability to use or the results of using the Service (including, without limitation, any direct, indirect, consequential, punitive, incidental, special or punitive damages, or any loss of revenue, profits, reputation, data, contracts, funds (whether in tort, contract or otherwise) for any loss of use, or loss or injury in any way arising out of or related to any business interruption of any kind of business. Even if the Company acknowledges in writing that it is liable to you for certain losses, you acknowledge and agree that the Company's entire liability to you, for whatever reason or in whatever manner of conduct, shall at all times not exceed the fees, if any, paid by you to the Company for the use of the services provided by the Software.",

    't8-7': `8.7 If a dispute arises between you and another user in connection with your use of the Service, you agree to pursue a claim or lawsuit against such user alone and will not request the Company's assistance in proving or naming the Company as a defendant, and you will not and will not hold the Company liable for all claims, liabilities and damages arising from any such claim or lawsuit in connection therewith.`,
    't8-8': `8.8 You use the Service to download or obtain any information at your own discretion and risk, and the Company shall not be liable for any damage to your computer system or loss of data as a result of the download of any information.`,
    't8-9': `8.9 The Company shall not be responsible for any activities organized by the User or any actions of any organization established by the User.`,
    't8-10': `8.10 For any activities planned, initiated, organized or undertaken by the Company (including but not limited to paid activities, public welfare activities), the Company does not make any guarantee or commitment to you for the effectiveness of the above activities, nor does it guarantee the legality or reasonableness of the User's conduct during the activities, and the Company shall not be liable for any personal or reputational, property or other damages to the User or others arising therefrom. 8.10.`,
    't8-11': `8.11 You understand and agree that in the course of using the Service, you may encounter force majeure and other risk factors that may cause interruption of the Service. Force majeure refers to objective events that cannot be foreseen, overcome and avoided and that have a significant impact on one or both parties, including but not limited to natural disasters such as floods, earthquakes, plague epidemics and storms, and social events such as war, unrest, governmental actions, etc. In the event of the above, the Company will endeavor to cooperate with the relevant units in the first instance and make timely repairs, but the Company and the relevant units are exempt from liability for any damage caused to you or third parties as a result thereof to the extent permitted by law.`,
    't8-12': `8.12 The Service, like most Internet services, may be affected by various security issues including, but not limited to, differences in your own reasons, network service quality, social environment and other factors, such as others using your information to cause real-life harassment; other software you download and install or other websites you visit contain "Trojan horses The viruses you download and install or visit from other websites contain "Trojan horses" and other viruses that threaten the security of your computer information and data, which in turn affects the normal use of the Service. You should strengthen the awareness of information security and protection of user data, and pay attention to strengthen password protection to avoid losses and harassment.`,
    't8-13': `8.13 You understand and agree that the Service is subject to the risk of service interruption or failure to meet user requirements due to force majeure, computer viruses or hacker attacks, system instability, user location, user shutdown, and any other technical, Internet, or communication line reasons, and the Company shall not be liable for any loss to you or third parties as a result.`,
    't9': '9. Declaration of Intellectual Property Rights',
    't9-1': `9.1 The intellectual property rights of the content provided by the Company in the Software and related services (including but not limited to software, technology, programs, web pages, text, pictures, images, audio, video, graphics, layout, electronic documents and all other data and information) belong to the Company. The copyrights, patents and other intellectual property rights of the software on which the Company provides the Software and related services are owned by the Company. No one may use the Software without the Company's permission.`,
    't9-2': `9.2 You understand and undertake that the content (including but not limited to text, images, video, audio and other forms of content and all components of music, sound, lines, visual design, etc. contained therein) that you post and upload while using the Software and related services is original to you or has been legally licensed (and includes sublicenses). The intellectual property rights in any Content that you upload or post through the Software belong to you or the original copyright owner.`,
    't9-3': `9.3 You acknowledge, understand and agree to grant to the Company and its affiliates, controlled companies, and successor companies a worldwide, royalty-free, non-exclusive, sublicensable (through multiple tiers) right in all forms of the Content (including, but not limited to, text, images, video, audio and all components of music, sound, lines, visual design, etc.) that you post and upload through the Software ( including, but not limited to, the right to store, use, reproduce, modify, edit, publish, display, translate, compile, adapt, create derivative works/derivative works of, distribute, transmit on an information network, perform, and incorporate the above information into other works in any form, media or technology known or hereafter developed). The scope of use includes, but is not limited to, current or other websites, applications, products or end devices, etc. You hereby acknowledge and agree that the grant of said rights includes the right and license to use and otherwise develop the Content (in whole or in part) in connection with any promotion, advertising, marketing and/or publicity relating to the Software, the Company and/or the Company's brands. For the avoidance of doubt, you agree that the grant of the above rights includes the right and license to use, reproduce and display your personal image, likeness, name, trademark, service mark, brand, name, logo and company mark (if any) and any other branding, marketing or promotional assets, materials, material, etc. that you own or are licensed to use and embed in the Content.`,
    't9-4': `9.4 You acknowledge and agree to authorize the Company to act on behalf of the Company in its own name or entrust a professional third party to defend the rights of content that infringes on the intellectual property rights that you have uploaded and posted, in the form of, but not limited to, monitoring infringement, sending a letter of defense, filing a lawsuit or arbitration, mediation, settlement, etc. The Company shall have the right to make decisions on matters of defense and implement them independently.`,
    't10': '10. Complaint reporting and breach of contract handling',

    't10-1': `10.1 The company has set up a public complaint and reporting channel, you can complain to the company, report all kinds of illegal and irregular behavior, illegal dissemination activities, illegal and harmful information and infringement information, etc. The company will accept and handle your complaints and reports in a timely manner, in order to jointly create a clean and upright cyberspace. Specific complaints and reports are detailed in Article 12.9 of this Agreement`,
    't10-2': `10.2 If the Company finds or receives reports or complaints from others that you have violated this Agreement and other agreements announced by the Company, the Company has the right to independently judge and take measures such as advance warning, refusal to publish, immediate stop transmission of information, deletion of comments, audio, video, audio and video content, short-term ban on speaking, restriction of some or all functions of the account until termination of the provision of services, and permanent closure of the account. The company has the right to announce the results of processing, and has the right to decide whether to resume the use of the relevant account according to the actual situation. For suspected violations of laws and regulations, suspected illegal and criminal acts, the company will keep the relevant records, and has the right to report to the relevant authorities, cooperate with the relevant authorities to investigate, report to the public security organs, etc. The company has the right not to restore the deleted content.`,
    't10-3': `10.3 Because you violate the provisions of this Agreement or other terms of service, caused by third-party complaints or litigation claims, you shall deal with and bear all the legal responsibility that may arise. If the Company and its affiliates, control companies, or successor companies pay compensation to any third party or suffer punishment from state authorities due to your illegal or breach of contract, you shall also compensate the Company and its affiliates, control companies, or successor companies in full for all losses suffered as a result.`,

    't11': '11. Changes, interruptions and termination of services',

    't11-1': '11.1 You understand and agree that the Company provides the Software and related services in accordance with the current status of existing technology and conditions. The Company will use its best efforts to provide the Services to you and to ensure the continuity and security of the Services. You understand that the Company cannot at any time foresee and protect against legal, technical and other risks, including but not limited to, service interruptions, data loss and other losses and risks that may result from force majeure, viruses, Trojan horses, hacker attacks, system instability, third party service defects and other various security issues.',

    't11-2': '11.2 The Company shall have the right to change, interrupt or terminate the provision of the Services to you without any liability to you in the event of any of the following circumstances:',

    't11-2-a': `a) the personal data provided by you is untrue or inconsistent with the information at the time of registration and fails to provide reasonable proof`,
    't11-2-b': `b)You violate the relevant laws and regulations or the agreement of this Agreement;`,
    't11-2-c': `c) In accordance with the provisions of the law or the requirements of the competent authorities;`,
    't11-2-d': `d) For security reasons or other necessary circumstances.`,

    't12': '12.Other',
    't12-1': `12.1 The Company solemnly reminds you of the clauses in this Agreement that exclude the Company's liability and limit your rights, so please read them carefully and consider the risks independently.`,
    't12-2': `The establishment, effectiveness, performance, interpretation and dispute resolution of this Agreement shall be governed by the law of Singapore. If any dispute or dispute arises between you and the company, it should first be resolved through friendly negotiation. If the negotiation fails, you agree to submit the dispute or dispute to the court with jurisdiction where the company is domiciled for resolution. You acknowledge that the company only provides a platform for you to communicate with other users, and you need to bear full responsibility for your own actions. If you have personal or property disputes or disputes with other members, the company is not obliged to handle them. You must resolve them through negotiation, mediation, litigation, etc. in accordance with relevant legal provisions.
    `,
    't12-3': `12.3 No matter any clause of this Agreement is invalid or unenforceable for whatever reason, the remaining clauses are still valid and binding on both parties.`,
    't12-4': `12.4 In order to provide you with better services or due to changes in national laws and regulations, policy adjustments, technical conditions, product features, etc., the Company may amend this Agreement from time to time, and the amendments shall form part of this Agreement. After this Agreement is updated, the Company will make an announcement in the Software or remind you of the updated contents by other appropriate means so that you can keep abreast of the latest version of this Agreement, and you can also check the latest version of the Agreement terms and conditions on the settings page of the Software. If you continue to use the Software and related services, you agree to accept the contents of this Agreement as amended.`,
    't12-5': `12.5 Due to the rapid development of the Internet, the terms and conditions set forth in this Agreement signed by you and the Company may not completely list and cover all your rights and obligations with the Company, and the existing agreement cannot guarantee full compliance with future development needs. Therefore, the Company's User Privacy Policy and the Platform Code of Conduct are supplementary agreements to this Agreement, which are inseparable from this Agreement and have the same legal effect. If you use the Service, you are deemed to agree to the aforementioned supplementary agreements.`,
    't12-6': `12.6 You and the Company are independent subjects and in no event shall this Agreement constitute an express or implied warranty or condition of any kind by the Company to you, nor shall it constitute an agency, partnership, joint venture or employment relationship between the parties.`,
    't12-7': `12.7 The headings in this Agreement are for convenience only and do not affect the meaning or interpretation of any provision of this Agreement.`,
    't12-8': `12.8 Any commercial activities or rewards entered into through the Software are independent of Apple Inc. and other application stores.`,
    't12-9': `12.9 If you have any questions, comments or suggestions regarding this Agreement, or if you find that the Software contains content that is illegal, violates this Agreement, or infringes on your personal rights such as reputation, portrait rights, privacy rights, or infringes on your intellectual property rights such as trademarks, patents, copyrights, etc., you may initiate a complaint or report by contacting us in the following ways:`,
    't12-9-1': `12.9.1 Email Report: Please follow the guidelines below and send an email to: xfunpetltd@gmail.com
    Title of the email: Yaame infringement complaint + the user name being reported
    Body of the email:
    `,
    't12-9-1-1': `1) Specific video link of the alleged infringement, description of the complaint, and attach "preliminary proof of infringement"`,
    't12-9-1-2': `(2) Declaration of authenticity: I am the legal right holder or agent of the content involved in this report, and my statements and materials provided in this report are true, valid and legal, and I guarantee to bear and compensate all the losses suffered by Yaame as a result of the processing of the complaint content according to this report.`,

    't12-9-2': `12.9.2 Reporting by letter: You may send the complaint document prepared in accordance with clause 12.9.1 by mail to the company at
    Company name: Xfun pte.ltd.
    `,

    't12-9-3': `12.9.3 Reporting within the APP: If you believe that another user you are videoing or chatting with has violated the law or rules, or infringed your legal rights and interests, you can:`,
    't12-9-3-1': `(1) Click on the round symbol in the upper right corner of the voice page, click on the "Report" pop-up, enter the report page, select or fill in the reason for the report, and upload relevant evidence materials to file a complaint.`,
    't12-9-3-2': `(2) In the session page, click the "More" button in the upper right corner, click the pop-up "Report" prompt, enter the report page, select or fill in the reason for the report, and upload relevant evidence materials to file a complaint.
    Once you initiate the "Report and Blackout" operation, you can mark the reported content and users, and the company will promptly remove the bad information after receiving your report; the company will also ensure that you will not be matched with the reported users in the future, so that you can completely block and intercept the reported users.
    The Company will process the reports of illegal and illegal information such as bad information within 24 hours and remove the relevant illegal and illegal information; for users who publish the aforementioned information, the Company will take measures including but not limited to restricting the matching privileges, account blocking, initialization or cancellation, account recovery, etc. in accordance with the provisions of clause 3.4.1 in accordance with the severity of the circumstances.
    `,


    't12-10': `12.10 The copyright of this Agreement is owned by the Company, and the Company reserves the right to interpret and amend it within the scope of the law.
    Special Notice:
    In view of the fact that the Company has clarified the above terms and fulfilled the obligations of the party who formulated the form terms, you will be deemed and should be deemed to have fully noted and agreed to the legality and validity of all the terms of this Agreement, especially the terms that remind you of them, and you should not claim or request the court or any other You shall not claim or request that a court or any other third party confirm the illegality or invalidity of the relevant terms and conditions on the grounds that the Company did not reasonably draw your attention to them or failed to do so. You have read and fully understood the terms and conditions of the above agreement, in particular the exclusion of liability clauses that exclude or limit the Company's liability, the clauses that limit the rights of users, the clauses that agree on dispute resolution, jurisdiction, and application of law, and agree to the entire content of the above agreement.
    `,

    't13': 'Refund Policy',
    'c13': '1  Unless otherwise specified, services purchased from the Sites are not refundable after purchase.',
};
